/**
 * Streaming client for the Express backend's `POST /api/chat/stream`
 * (see `server/api/chat.js`). `EventSource` can't send a POST body, so
 * this reads the fetch() response body as raw SSE by hand: `event: <name>`
 * + `data: <payload>` pairs, separated by blank lines.
 */
import type { MessageRole } from "@/features/copilot/types";
import type { StructuredEvaluation } from "@/features/recruiter-mode/types";
import { getApiUrl } from "@/lib/utils";

export interface ChatHistoryMessage {
  role: MessageRole;
  content: string;
}

export interface StreamChatOptions {
  messages: ChatHistoryMessage[];
  signal: AbortSignal;
  /** Session ID generated by the client. When provided, the server uses its
   *  stored session history to build context — the client only needs to send
   *  the new user message, not the full thread. */
  sessionId?: string;
  onDelta: (text: string) => void;
  onAgentRouting?: (agents: string[]) => void;
  onExecutionPlan?: (plan: string[]) => void;
  onFollowUps?: (suggestions: string[]) => void;
  onProvider?: (provider: string) => void;
  onRouteClassification?: (route: string) => void;
  onTopicTags?: (topics: string[]) => void;
  onRagMetrics?: (metrics: Array<{ label: string; cosineScore: number; rerankScore: number }>) => void;
  onToolCall?: (toolCall: { name: string; args: any; result: any }) => void;
  onStructuredEval?: (structuredEval: StructuredEvaluation) => void;
}

export class ChatStreamError extends Error {
  code: string;
  /** True if some tokens had already streamed before this error fired —
   * callers can keep the partial reply instead of discarding it. */
  partial: boolean;

  constructor(message: string, { code, partial }: { code: string; partial: boolean }) {
    super(message);
    this.name = "ChatStreamError";
    this.code = code;
    this.partial = partial;
  }
}

function parseSseBlock(block: string): { event: string; data: string } | null {
  let event = "message";
  const dataLines: string[] = [];

  for (const rawLine of block.split("\n")) {
    const line = rawLine.trimEnd();
    if (!line || line.startsWith(":")) continue;
    if (line.startsWith("event:")) {
      event = line.slice(6).trim();
    } else if (line.startsWith("data:")) {
      dataLines.push(line.slice(5).trim());
    }
  }

  if (dataLines.length === 0) return null;
  return { event, data: dataLines.join("\n") };
}

/** POSTs the conversation to the chat-stream endpoint and calls `onDelta`
 * for each token as it arrives. Resolves once the server sends `done`,
 * rejects with `ChatStreamError` on a network failure or a server-sent
 * `error` event. */
export async function streamChatCompletion({
  messages,
  signal,
  sessionId,
  onDelta,
  onAgentRouting,
  onExecutionPlan,
  onFollowUps,
  onProvider,
  onRouteClassification,
  onTopicTags,
  onRagMetrics,
  onToolCall,
  onStructuredEval,
}: StreamChatOptions): Promise<void> {
  let response: Response;
  try {
    response = await fetch(getApiUrl("/api/chat/stream"), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ messages, ...(sessionId ? { sessionId } : {}) }),
      signal,
    });
  } catch (err) {
    if ((err as { name?: string })?.name === "AbortError") throw err;
    throw new ChatStreamError("Couldn't reach the server. Check your connection and try again.", {
      code: "NETWORK_ERROR",
      partial: false,
    });
  }

  if (!response.ok || !response.body) {
    let message = `The server returned an error (${response.status}).`;
    try {
      const body = await response.json();
      if (body?.message) message = body.message;
    } catch {
      // Non-JSON error body — fall back to the generic status message above.
    }
    throw new ChatStreamError(message, { code: "HTTP_ERROR", partial: false });
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let sawAnyDelta = false;
  let sawDoneEvent = false;

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const blocks = buffer.split("\n\n");
      buffer = blocks.pop() ?? "";

      for (const block of blocks) {
        const parsed = parseSseBlock(block);
        if (!parsed) continue;

        if (parsed.event === "delta") {
          try {
            const { text } = JSON.parse(parsed.data) as { text: string };
            if (text) {
              sawAnyDelta = true;
              onDelta(text);
            }
          } catch {
            // Malformed delta payload — skip rather than crash the stream.
          }
        } else if (parsed.event === "route-classification") {
          try {
            const { route } = JSON.parse(parsed.data) as { route: string };
            if (route && onRouteClassification) {
              onRouteClassification(route);
            }
          } catch {}
        } else if (parsed.event === "topic-tags") {
          try {
            const { topics } = JSON.parse(parsed.data) as { topics: string[] };
            if (topics && onTopicTags) {
              onTopicTags(topics);
            }
          } catch {}
        } else if (parsed.event === "rag-metrics") {
          try {
            const { ragMetrics } = JSON.parse(parsed.data) as { ragMetrics: Array<{ label: string; cosineScore: number; rerankScore: number }> };
            if (ragMetrics && onRagMetrics) {
              onRagMetrics(ragMetrics);
            }
          } catch {}
        } else if (parsed.event === "tool-call") {
          try {
            const { toolCall } = JSON.parse(parsed.data) as { toolCall: { name: string; args: any; result: any } };
            if (toolCall && onToolCall) {
              onToolCall(toolCall);
            }
          } catch {}
        } else if (parsed.event === "structured-eval") {
          try {
            const { structuredEval } = JSON.parse(parsed.data) as { structuredEval: StructuredEvaluation };
            if (structuredEval && onStructuredEval) {
              onStructuredEval(structuredEval);
            }
          } catch {}
        } else if (parsed.event === "agent-routing") {
          try {
            const { agents } = JSON.parse(parsed.data) as { agents: string[] };
            if (agents && onAgentRouting) {
              onAgentRouting(agents);
            }
          } catch {
            // ignore
          }
        } else if (parsed.event === "execution-plan") {
          try {
            const { plan } = JSON.parse(parsed.data) as { plan: string[] };
            if (plan && onExecutionPlan) {
              onExecutionPlan(plan);
            }
          } catch {}
        } else if (parsed.event === "follow-ups") {
          try {
            const { followUps } = JSON.parse(parsed.data) as { followUps: string[] };
            if (followUps && onFollowUps) {
              onFollowUps(followUps);
            }
          } catch {}
        } else if (parsed.event === "provider") {
          try {
            const { provider } = JSON.parse(parsed.data) as { provider: string };
            if (provider && onProvider) {
              onProvider(provider);
            }
          } catch {}
        } else if (parsed.event === "error") {
          let message = "The assistant hit an error generating a reply.";
          let code = "STREAM_ERROR";
          try {
            const payload = JSON.parse(parsed.data) as { message?: string; code?: string };
            if (payload.message) message = payload.message;
            if (payload.code) code = payload.code;
          } catch {
            // Fall back to the defaults above.
          }
          throw new ChatStreamError(message, { code, partial: sawAnyDelta });
        } else if (parsed.event === "done") {
          sawDoneEvent = true;
          return;
        }
      }
    }

    if (!sawDoneEvent && !sawAnyDelta) {
      throw new ChatStreamError("The connection closed before a reply was received.", {
        code: "STREAM_CLOSED",
        partial: false,
      });
    }
  } finally {
    reader.releaseLock();
  }
}
