const fs = require("fs");
const path = require("path");

const PROFILE_TS_PATH = path.resolve(__dirname, "../src/content/profile.ts");
const DATA_JS_PATH = path.resolve(__dirname, "../public/legacy/data.js");

function syncLegacyData() {
  const tsContent = fs.readFileSync(PROFILE_TS_PATH, "utf8");

  // Extract the PORTFOLIO object literal from src/content/profile.ts
  const match = tsContent.match(/export const PORTFOLIO: PortfolioData = ([\s\S]*?);\s*export default PORTFOLIO;/);
  if (!match) {
    throw new Error("Could not parse PORTFOLIO object from src/content/profile.ts");
  }

  const portfolioObjectStr = match[1];

  const header = `/* ============================================================================
   PORTFOLIO DATA (AUTO-GENERATED FROM src/content/profile.ts)
   ----------------------------------------------------------------------------
   DO NOT EDIT THIS FILE DIRECTLY.
   Edit \`src/content/profile.ts\` instead.
   Then run \`npm run kb:rebuild\` to sync both the site UI and chatbot knowledge.
   ============================================================================ */

const PORTFOLIO = ${portfolioObjectStr};

window.PORTFOLIO = PORTFOLIO;
`;

  fs.writeFileSync(DATA_JS_PATH, header, "utf8");
  console.log(`Synced ${path.relative(process.cwd(), PROFILE_TS_PATH)} -> ${path.relative(process.cwd(), DATA_JS_PATH)}`);
}

if (require.main === module) {
  syncLegacyData();
}

module.exports = { syncLegacyData };
